### ISSUE TITLE
Agregar animación a tarjeta de productos

### ISSUE THREAD

**Issue by gabrieldominguezdh10** [martasgo/mercado-liebre-martabutti#2]
- Se debe agregar una transicion al hacer hover sobre tarjeta de producto para que muestre mas información sobre el producto.

- El camión debe orientarse apuntando hacia arriba al hacer hover.

Sin hover:
![image](https://github.com/martasgo/mercado-liebre-martabutti/assets/147005581/d007a468-b9f9-468d-91db-5f8e8cf872b2)

Con hover:
![image](https://github.com/martasgo/mercado-liebre-martabutti/assets/147005581/64f399dd-797d-4826-bddb-d1a7489c5824)

**Comment by martasgo** [comment]
Buenas tardes profe, como está? según la indicación del proyecto cuando se hace hover sobre la imagen debia mostrarse una sombra y el texto de la descripción, si lo verifica en la versión web está asi. Y en la segunda foto que usted me manda aparece la descripción.
Respecto al camión si tiene la animación, en el practico se pedía que cuando se haga hover sobre el camión debía girar hacia arriba y asi está implementado. 

En mobile estos efectos no se ven salvo se haga click en la imagen. 

No sé si estoy entendiendo bien la revisión que me hace profe disculpe.

**Comment by gabrieldominguezdh10** [comment]
Marta no te preocupes. 

La consigna comenta lo siguiente:

"Otro efecto (*) que nos piden es el que podemos ver en las siguientes imágenes,
donde el ícono del camión de envío gira 90° hacia arriba suavemente cuando
pasamos el mouse por encima."

Tenemos un trabajo realizado por alumnos egresados en donde la animación se daba haciendo hover sobre cualquier lugar de la tarjeta de producto.

La consigna puede parecer ambigua quizá.

No te preocupes por modificar esa parte. La misma aclaración se la voy a hacer a todos los alumnos oportunamente.

Gracias por responder. 

Saludos

**Comment by martasgo** [comment]
Profe buenas tardes,
Disculpe recién me doy cuenta que no había respondido este último mensaje.

Entonces cierro el issue sin hacer nada, es lo que entiendo, es asi?

Saludos
